author: "Nguyễn Văn Bảy"
maked_at: "© 2019"
VALID_EMAIL_REGEX: !ruby/regexp '/\A[a-zA-Z0-9_\.]+\z/i'
max_username: 200
min_password: 3
min_name: 1
max_name: 100
min_phone: 3
max_phone: 25
min_address: 3
max_address: 250
num_user: 10
url_avata: "https://bootdey.com/img/Content/user_1.jpg"
theme_config: "twitter-bootstrap-3"
num_product: 10
unit: "VND"
num_combo_product: 10
num_combo: 10
min_name_product: 3
max_name_product: 250
min_name_combo: 3
max_name_combo: 250
